Dynamic Hashing:
	Motivation for Dynamic Hashing : To ensuere good perfromance
is is necessary to increase the size of a hash table whenever its loading
density exceeds a prespecified threshold.

Example for Dynamic hashing using Directories:
Initally
	....
	 00  -> A0 B0
	....
	 01  -> A1 B1
	....
	 10  -> C2
	....
	 11   -> C3
	....
	Depth =2

Once capaccity about to complete we need to increse the depth
	....
	000  -> A0 B0
	....
	 001  -> A1 B1
	....
	 010  -> C2
	....
	 011   -> C3
	....
	 100
	 ....
	 101 -> c5
	....
	 110  ->
	....
	 111 ->
	....

Note: Depth Increases.

